// Code generated by "genprotocol -ver=ae6ffb3d00fdbd5fe4a5f3bcd7c7daed9e931f80784dc997a7ece55b7638f5c1 -basedir=. -prefix=t2g"

package t2g_obj

import (
	"github.com/kasworld/goguelike/config/towerconfig"
	"github.com/kasworld/goguelike/game/aoscore"
	"github.com/kasworld/goguelike/protocol_c2t/c2t_obj"
)

type ReqInvalid_data struct {
	Dummy uint8
}
type RspInvalid_data struct {
	Dummy uint8
}

type ReqRegister_data struct {
	TI *c2t_obj.TowerInfo
	SI *c2t_obj.ServiceInfo
	TC *towerconfig.TowerConfig
}
type RspRegister_data struct {
	Dummy uint8
}

type ReqHeartbeat_data struct {
	TowerUUID  string
	StatusInfo []string
}
type RspHeartbeat_data struct {
	Dummy uint8
}

type ReqHighScore_data struct {
	ActiveObjScore *aoscore.ActiveObjScore
}
type RspHighScore_data struct {
	Dummy uint8
}
