// Code generated by "genprotocol.exe -ver=4761917555d922e5951aa6c3aee428ba5acda663bf281621426dc91134d9ffa7 -basedir=protocol_t2g -prefix=t2g -statstype=int"

package t2g_handlereq

import (
	"fmt"

	"github.com/kasworld/goguelike/protocol_t2g/t2g_error"
	"github.com/kasworld/goguelike/protocol_t2g/t2g_idcmd"
	"github.com/kasworld/goguelike/protocol_t2g/t2g_obj"
	"github.com/kasworld/goguelike/protocol_t2g/t2g_packet"
)

// obj base demux fn map
var DemuxReq2ObjAPIFnMap = [...]func(
	me interface{}, hd t2g_packet.Header, robj interface{}) (
	t2g_packet.Header, interface{}, error){
	t2g_idcmd.Invalid:   Req2ObjAPI_Invalid,   // Invalid make empty packet error
	t2g_idcmd.Register:  Req2ObjAPI_Register,  // Register
	t2g_idcmd.Heartbeat: Req2ObjAPI_Heartbeat, // Heartbeat
	t2g_idcmd.HighScore: Req2ObjAPI_HighScore, // HighScore

} // DemuxReq2ObjAPIFnMap

// Invalid make empty packet error
func Req2ObjAPI_Invalid(
	me interface{}, hd t2g_packet.Header, robj interface{}) (
	t2g_packet.Header, interface{}, error) {
	req, ok := robj.(*t2g_obj.ReqInvalid_data)
	if !ok {
		return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
	}
	rhd, rsp, err := objAPIFn_ReqInvalid(me, hd, req)
	return rhd, rsp, err
}

// Invalid make empty packet error
func objAPIFn_ReqInvalid(
	me interface{}, hd t2g_packet.Header, robj *t2g_obj.ReqInvalid_data) (
	t2g_packet.Header, *t2g_obj.RspInvalid_data, error) {
	sendHeader := t2g_packet.Header{
		ErrorCode: t2g_error.None,
	}
	sendBody := &t2g_obj.RspInvalid_data{}
	return sendHeader, sendBody, nil
}

// Register
func Req2ObjAPI_Register(
	me interface{}, hd t2g_packet.Header, robj interface{}) (
	t2g_packet.Header, interface{}, error) {
	req, ok := robj.(*t2g_obj.ReqRegister_data)
	if !ok {
		return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
	}
	rhd, rsp, err := objAPIFn_ReqRegister(me, hd, req)
	return rhd, rsp, err
}

// Register
func objAPIFn_ReqRegister(
	me interface{}, hd t2g_packet.Header, robj *t2g_obj.ReqRegister_data) (
	t2g_packet.Header, *t2g_obj.RspRegister_data, error) {
	sendHeader := t2g_packet.Header{
		ErrorCode: t2g_error.None,
	}
	sendBody := &t2g_obj.RspRegister_data{}
	return sendHeader, sendBody, nil
}

// Heartbeat
func Req2ObjAPI_Heartbeat(
	me interface{}, hd t2g_packet.Header, robj interface{}) (
	t2g_packet.Header, interface{}, error) {
	req, ok := robj.(*t2g_obj.ReqHeartbeat_data)
	if !ok {
		return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
	}
	rhd, rsp, err := objAPIFn_ReqHeartbeat(me, hd, req)
	return rhd, rsp, err
}

// Heartbeat
func objAPIFn_ReqHeartbeat(
	me interface{}, hd t2g_packet.Header, robj *t2g_obj.ReqHeartbeat_data) (
	t2g_packet.Header, *t2g_obj.RspHeartbeat_data, error) {
	sendHeader := t2g_packet.Header{
		ErrorCode: t2g_error.None,
	}
	sendBody := &t2g_obj.RspHeartbeat_data{}
	return sendHeader, sendBody, nil
}

// HighScore
func Req2ObjAPI_HighScore(
	me interface{}, hd t2g_packet.Header, robj interface{}) (
	t2g_packet.Header, interface{}, error) {
	req, ok := robj.(*t2g_obj.ReqHighScore_data)
	if !ok {
		return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
	}
	rhd, rsp, err := objAPIFn_ReqHighScore(me, hd, req)
	return rhd, rsp, err
}

// HighScore
func objAPIFn_ReqHighScore(
	me interface{}, hd t2g_packet.Header, robj *t2g_obj.ReqHighScore_data) (
	t2g_packet.Header, *t2g_obj.RspHighScore_data, error) {
	sendHeader := t2g_packet.Header{
		ErrorCode: t2g_error.None,
	}
	sendBody := &t2g_obj.RspHighScore_data{}
	return sendHeader, sendBody, nil
}
