// Code generated by "genprotocol.exe -ver=4761917555d922e5951aa6c3aee428ba5acda663bf281621426dc91134d9ffa7 -basedir=protocol_t2g -prefix=t2g -statstype=int"

package t2g_handlersp

import (
	"fmt"

	"github.com/kasworld/goguelike/protocol_t2g/t2g_idcmd"
	"github.com/kasworld/goguelike/protocol_t2g/t2g_json"
	"github.com/kasworld/goguelike/protocol_t2g/t2g_obj"
	"github.com/kasworld/goguelike/protocol_t2g/t2g_packet"
)

// bytes base demux fn map

var DemuxRsp2BytesFnMap = [...]func(me interface{}, hd t2g_packet.Header, rbody []byte) error{
	t2g_idcmd.Invalid:   bytesRecvRspFn_Invalid,   // Invalid make empty packet error
	t2g_idcmd.Register:  bytesRecvRspFn_Register,  // Register
	t2g_idcmd.Heartbeat: bytesRecvRspFn_Heartbeat, // Heartbeat
	t2g_idcmd.HighScore: bytesRecvRspFn_HighScore, // HighScore

}

// Invalid make empty packet error
func bytesRecvRspFn_Invalid(me interface{}, hd t2g_packet.Header, rbody []byte) error {
	robj, err := t2g_json.UnmarshalPacket(hd, rbody)
	if err != nil {
		return fmt.Errorf("Packet type miss match %v", rbody)
	}
	recved, ok := robj.(*t2g_obj.RspInvalid_data)
	if !ok {
		return fmt.Errorf("packet mismatch %v", robj)
	}
	return fmt.Errorf("Not implemented %v", recved)
}

// Register
func bytesRecvRspFn_Register(me interface{}, hd t2g_packet.Header, rbody []byte) error {
	robj, err := t2g_json.UnmarshalPacket(hd, rbody)
	if err != nil {
		return fmt.Errorf("Packet type miss match %v", rbody)
	}
	recved, ok := robj.(*t2g_obj.RspRegister_data)
	if !ok {
		return fmt.Errorf("packet mismatch %v", robj)
	}
	return fmt.Errorf("Not implemented %v", recved)
}

// Heartbeat
func bytesRecvRspFn_Heartbeat(me interface{}, hd t2g_packet.Header, rbody []byte) error {
	robj, err := t2g_json.UnmarshalPacket(hd, rbody)
	if err != nil {
		return fmt.Errorf("Packet type miss match %v", rbody)
	}
	recved, ok := robj.(*t2g_obj.RspHeartbeat_data)
	if !ok {
		return fmt.Errorf("packet mismatch %v", robj)
	}
	return fmt.Errorf("Not implemented %v", recved)
}

// HighScore
func bytesRecvRspFn_HighScore(me interface{}, hd t2g_packet.Header, rbody []byte) error {
	robj, err := t2g_json.UnmarshalPacket(hd, rbody)
	if err != nil {
		return fmt.Errorf("Packet type miss match %v", rbody)
	}
	recved, ok := robj.(*t2g_obj.RspHighScore_data)
	if !ok {
		return fmt.Errorf("packet mismatch %v", robj)
	}
	return fmt.Errorf("Not implemented %v", recved)
}
