// Code generated by "genprotocol -ver=63636f8539b161fecb680e8fbe21f71f444a916426f67ba0aa97f6820401b7f1 -basedir=. -prefix=t2g"

package t2g_const

import "time"

const (
	// MaxBodyLen set to max body len, affect send/recv buffer size
	MaxBodyLen = 0xfffff

	// ServerAPICallTimeOutDur api call watchdog timer
	ServerAPICallTimeOutDur = time.Second * 2
)
