// Code generated by "genprotocol.exe -ver=4761917555d922e5951aa6c3aee428ba5acda663bf281621426dc91134d9ffa7 -basedir=protocol_t2g -prefix=t2g -statstype=int"

package t2g_handlenoti

import (
	"fmt"

	"github.com/kasworld/goguelike/protocol_t2g/t2g_idnoti"
	"github.com/kasworld/goguelike/protocol_t2g/t2g_json"
	"github.com/kasworld/goguelike/protocol_t2g/t2g_obj"
	"github.com/kasworld/goguelike/protocol_t2g/t2g_packet"
)

// bytes base demux fn map

var DemuxNoti2ByteFnMap = [...]func(me interface{}, hd t2g_packet.Header, rbody []byte) error{
	t2g_idnoti.Invalid: bytesRecvNotiFn_Invalid, // Invalid make empty packet error

}

// Invalid make empty packet error
func bytesRecvNotiFn_Invalid(me interface{}, hd t2g_packet.Header, rbody []byte) error {
	robj, err := t2g_json.UnmarshalPacket(hd, rbody)
	if err != nil {
		return fmt.Errorf("Packet type miss match %v", rbody)
	}
	recved, ok := robj.(*t2g_obj.NotiInvalid_data)
	if !ok {
		return fmt.Errorf("packet mismatch %v", robj)
	}
	return fmt.Errorf("Not implemented %v", recved)
}
