// Code generated by "genprotocol -ver=7710be9929fb34398fedf9489d8543e9bb25cd058bac35b9624c421db5a4157a -basedir=. -prefix=c2t"

package c2t_const

import "time"

const (
	// MaxBodyLen set to max body len, affect send/recv buffer size
	MaxBodyLen = 0xfffff
)

const (
	// ServerAPICallTimeOutDur api call watchdog timer
	ServerAPICallTimeOutDur = time.Second * 2
)
